services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build:
      context: ./backend/api
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    build:
      context: ./backend/db
    ports:
      - "5432:5432"
